week2hwv1
Lidemy/mentor-program-5th-ming94114 pull request #2
Opened 2021-04-28 18:15 UTC by ming94114

2021-04-29 15:24 UTC, cwc329 requested changes
大致上來說寫得不錯！

建議 hw6 再描述得詳細一些，
另外給一些 edge case，可以考慮一下要怎麼處理。

都是些小問題，你可以自己 merge 之後再開新 branch 訂正，或者在這個 PR 訂正。訂正後可以 tag 我，我會再來看。

2021-04-29 15:24 UTC, cwc329 commented on homeworks/week2/hw1.js
> +
無意義的空行，建議移除。

2021-04-29 15:24 UTC, cwc329 commented on homeworks/week2/hw2.js
>  }
傳空字串會怎樣呢？

2021-04-29 15:24 UTC, cwc329 commented on homeworks/week2/hw5.js
>  }
傳空陣列呢？
可以看看內建函式是怎麼處理的。

2021-04-29 15:24 UTC, cwc329 commented on homeworks/week2/hw6.md
> +15. 執行第6行，檢查 arr[2] 等於8，是否不等於 arr[0] + arr[1]，否(兩者相加為8
arr[0] 與 arr[1] 的值各是什麼？

2021-04-29 15:24 UTC, cwc329 reviewed
剛剛點錯選項

2021-04-29 15:24 UTC, cwc329 approved these changes

2021-04-29 15:26 UTC, cwc329 commented
然後建議把檔案中沒有意義的 console.log 與 function call 移除。

2021-05-06 13:44 UTC, ming94114 commented on homeworks/week2/hw6.md
> +15. 執行第6行，檢查 arr[2] 等於8，是否不等於 arr[0] + arr[1]，否(兩者相加為8
@cwc329 抱歉在看第三週進度所以拖得有點久，在麻煩助教

2021-05-09 01:32 UTC, cwc329 approved these changes

2021-05-09 01:32 UTC, merged

2021-05-09 01:33 UTC, cwc329 commented
hw6 有訂正給推！

程式題 edge case 到不份之後有時間的話可以再回來想看看。